CREATE TABLE IF NOT EXISTS users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  name varchar(255),
  email varchar(512),
  CONSTRAINT pk_user PRIMARY KEY (id),
  CONSTRAINT UQ_USER_EMAIL UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS item_requests (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  description varchar(512),
  requester_id BIGINT,
  created TIMESTAMP WITH TIME ZONE,
  FOREIGN KEY (requester_id) REFERENCES users (id),
  CONSTRAINT item_requests_id PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  name varchar(255) NOT NULL,
  description varchar(512)NOT NULL,
  available boolean,
  owner BIGINT,
  request_id BIGINT,
  FOREIGN KEY (request_id) REFERENCES item_requests (id),
  CONSTRAINT item_id PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS bookings (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  start TIMESTAMP WITH TIME ZONE,
  end_time TIMESTAMP WITH TIME ZONE,
  item_id BIGINT,
  booker_id BIGINT,
  status varchar(8),
  FOREIGN KEY (item_id) REFERENCES items (id),
  FOREIGN KEY (booker_id) REFERENCES users (id),
  CONSTRAINT booking_id PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS comments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  text varchar(512),
  item_id BIGINT,
  author_id BIGINT,
  created TIMESTAMP WITH TIME ZONE,
  FOREIGN KEY (item_id) REFERENCES items (id),
  FOREIGN KEY (author_id) REFERENCES users (id),
  CONSTRAINT comment_id PRIMARY KEY (id)
);

DELETE FROM users CASCADE;
DELETE FROM item_requests CASCADE;
DELETE FROM items CASCADE;
DELETE FROM bookings CASCADE;
DELETE FROM comments CASCADE;

ALTER TABLE items ADD FOREIGN KEY (owner) REFERENCES users (id);
